import React from "react";
import Leaderboard from "~/app/_components/Leaderboard"; // Adjust path if needed

const data = [
  {
    teamName: "Alpha Innovators",
    teamLeader: "Chris Lopes",
    design: "8",
    functionality: "9",
    innovation: "10",
    feasibility: "7",
    userExperience: "9",
    scalability: "8",
    demonstration: "9",
    total: "60",
  },
  {
    teamName: "Tech Titans",
    teamLeader: "Jane Doe",
    design: "9",
    functionality: "8",
    innovation: "9",
    feasibility: "8",
    userExperience: "9",
    scalability: "7",
    demonstration: "9",
    total: "59",
  },
  {
    teamName: "Code Masters",
    teamLeader: "John Smith",
    design: "7",
    functionality: "8",
    innovation: "8",
    feasibility: "9",
    userExperience: "8",
    scalability: "9",
    demonstration: "8",
    total: "57",
  },
  {
    teamName: "Alpha Innovators",
    teamLeader: "Chris Lopes",
    design: "8",
    functionality: "9",
    innovation: "10",
    feasibility: "7",
    userExperience: "9",
    scalability: "8",
    demonstration: "9",
    total: "60",
  },
  {
    teamName: "Tech Titans",
    teamLeader: "Jane Doe",
    design: "9",
    functionality: "8",
    innovation: "9",
    feasibility: "8",
    userExperience: "9",
    scalability: "7",
    demonstration: "9",
    total: "59",
  },
  {
    teamName: "Code Masters",
    teamLeader: "John Smith",
    design: "7",
    functionality: "8",
    innovation: "8",
    feasibility: "9",
    userExperience: "8",
    scalability: "9",
    demonstration: "8",
    total: "57",
  },
  {
    teamName: "Alpha Innovators",
    teamLeader: "Chris Lopes",
    design: "8",
    functionality: "9",
    innovation: "10",
    feasibility: "7",
    userExperience: "9",
    scalability: "8",
    demonstration: "9",
    total: "60",
  },
  {
    teamName: "Tech Titans",
    teamLeader: "Jane Doe",
    design: "9",
    functionality: "8",
    innovation: "9",
    feasibility: "8",
    userExperience: "9",
    scalability: "7",
    demonstration: "9",
    total: "59",
  },
  {
    teamName: "Code Masters",
    teamLeader: "John Smith",
    design: "7",
    functionality: "8",
    innovation: "8",
    feasibility: "9",
    userExperience: "8",
    scalability: "9",
    demonstration: "8",
    total: "57",
  },
  {
    teamName: "Alpha Innovators",
    teamLeader: "Chris Lopes",
    design: "8",
    functionality: "9",
    innovation: "10",
    feasibility: "7",
    userExperience: "9",
    scalability: "8",
    demonstration: "9",
    total: "60",
  },
  {
    teamName: "Tech Titans",
    teamLeader: "Jane Doe",
    design: "9",
    functionality: "8",
    innovation: "9",
    feasibility: "8",
    userExperience: "9",
    scalability: "7",
    demonstration: "9",
    total: "59",
  },
  {
    teamName: "Code Masters",
    teamLeader: "John Smith",
    design: "7",
    functionality: "8",
    innovation: "8",
    feasibility: "9",
    userExperience: "8",
    scalability: "9",
    demonstration: "8",
    total: "57",
  },
  {
    teamName: "Alpha Innovators",
    teamLeader: "Chris Lopes",
    design: "8",
    functionality: "9",
    innovation: "10",
    feasibility: "7",
    userExperience: "9",
    scalability: "8",
    demonstration: "9",
    total: "60",
  },
  {
    teamName: "Tech Titans",
    teamLeader: "Jane Doe",
    design: "9",
    functionality: "8",
    innovation: "9",
    feasibility: "8",
    userExperience: "9",
    scalability: "7",
    demonstration: "9",
    total: "59",
  },
  {
    teamName: "Code Masters",
    teamLeader: "John Smith",
    design: "7",
    functionality: "8",
    innovation: "8",
    feasibility: "9",
    userExperience: "8",
    scalability: "9",
    demonstration: "8",
    total: "57",
  },
  {
    teamName: "Alpha Innovators",
    teamLeader: "Chris Lopes",
    design: "8",
    functionality: "9",
    innovation: "10",
    feasibility: "7",
    userExperience: "9",
    scalability: "8",
    demonstration: "9",
    total: "60",
  },
  {
    teamName: "Tech Titans",
    teamLeader: "Jane Doe",
    design: "9",
    functionality: "8",
    innovation: "9",
    feasibility: "8",
    userExperience: "9",
    scalability: "7",
    demonstration: "9",
    total: "59",
  },
  {
    teamName: "Code Masters",
    teamLeader: "John Smith",
    design: "7",
    functionality: "8",
    innovation: "8",
    feasibility: "9",
    userExperience: "8",
    scalability: "9",
    demonstration: "8",
    total: "57",
  },
  {
    teamName: "Alpha Innovators",
    teamLeader: "Chris Lopes",
    design: "8",
    functionality: "9",
    innovation: "10",
    feasibility: "7",
    userExperience: "9",
    scalability: "8",
    demonstration: "9",
    total: "60",
  },
  {
    teamName: "Tech Titans",
    teamLeader: "Jane Doe",
    design: "9",
    functionality: "8",
    innovation: "9",
    feasibility: "8",
    userExperience: "9",
    scalability: "7",
    demonstration: "9",
    total: "59",
  },
  {
    teamName: "Code Masters",
    teamLeader: "John Smith",
    design: "7",
    functionality: "8",
    innovation: "8",
    feasibility: "9",
    userExperience: "8",
    scalability: "9",
    demonstration: "8",
    total: "57",
  },
  // Add more team data as needed
];

export default function Home() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-black p-4">
      <Leaderboard data={data} />
    </div>
  );
}
